//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mStructural {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class appsetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static appsetting defaultInstance = ((appsetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appsetting())));
        
        public static appsetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ViewGap {
            get {
                return ((double)(this["ViewGap"]));
            }
            set {
                this["ViewGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\BendTech\\Library\\02-DESIGN LIBRARY\\BT LIBRARY\\START MODELS")]
        public string StartModelPath {
            get {
                return ((string)(this["StartModelPath"]));
            }
            set {
                this["StartModelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ETCHING;ETCHING (TYP);LINE ETCHING;LINE ETCHING (TYP);SLOT;2x SLOTS")]
        public string EdgeNote {
            get {
                return ((string)(this["EdgeNote"]));
            }
            set {
                this["EdgeNote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Programming\\MasterPlatform\\PlatformAutomation")]
        public string PAMasterPath {
            get {
                return ((string)(this["PAMasterPath"]));
            }
            set {
                this["PAMasterPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\MaxwellWG\\Desktop\\PA Target")]
        public string PATargetPath {
            get {
                return ((string)(this["PATargetPath"]));
            }
            set {
                this["PATargetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeleteTubeLaserBodyLoc {
            get {
                return ((string)(this["DeleteTubeLaserBodyLoc"]));
            }
            set {
                this["DeleteTubeLaserBodyLoc"] = value;
            }
        }
    }
}
